my_oa_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^oa_core/', include('oa_core.urls', namespace="oa_core")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls'))
]

oa_core/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    # post views
    url(r'^register/$', views.em_register, name='register'),
    url(r'^register_success/$', views.register_success, name='register_success'),
    url(r'^login/$', views.login, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^user_center/$', views.user_center, name='user_center'),
    url(r'^user_info_update/$', views.user_info_update, name='user_info_update'),
    url(r'^user_password_update/$', views.user_password_update, name='user_password_update'),
    url(r'^all_employees/$', views.all_employees, name='all_employees'),
    url(r'^all_managers/$', views.all_managers, name='all_managers'),
    url(r'^all_ceo/$', views.all_ceo, name='all_ceo'),
    url(r'^user_detail/(?P<user_id>[emc]_[0-9]+)/$', views.user_detail, name='user_detail'),
    url(r'^company_news/$', views.company_news, name='company_news'),
    url(r'^show_news/(?P<news_id>[0-9]+)$', views.show_news, name='show_news'),



    url(r'^holiday/$', views.my_holiday_tasks, name='my_holiday_tasks'),
    url(r'^holiday/add/$', views.add_holiday_task, name='add_holiday_task'),
    url(r'^holiday/(?P<ht_id>[0-9]+)/$', views.holiday_task_detail, name='holiday_task_detail'),
    url(r'^holiday/update/(?:(?P<ht_id>[0-9]+)/)?$', views.update_holiday_task, name='update_holiday_task'),
    url(r'^holiday/delete/(?P<ht_id>[0-9]+)/$', views.holiday_task_delete, name='holiday_task_delete'),
    url(r'^holiday/submit/(?P<ht_id>[0-9]+)/$', views.holiday_task_submit, name='holiday_task_submit'),
    url(r'^holiday/withdraw/(?P<ht_id>[0-9]+)/$', views.holiday_task_withdraw, name='holiday_task_withdraw'),

    url(r'^holiday/subordinate_tasks/$', views.subordinate_holiday_tasks, name='subordinate_holiday_tasks'),
    url(r'^holiday/approve/(?P<ht_id>[0-9]+)/$', views.holiday_task_approve, name='holiday_task_approve'),
    url(r'^holiday/negative/(?P<ht_id>[0-9]+)/$', views.holiday_task_negative, name='holiday_task_negative'),

    url(r'^overtime/$', views.my_overtime_tasks, name='my_overtime_tasks'),
    url(r'^overtime/add/$', views.add_overtime_task, name='add_overtime_task'),
    url(r'^overtime/(?P<ot_id>[0-9]+)/$', views.overtime_task_detail, name='overtime_task_detail'),
    url(r'^overtime/update/(?:(?P<ot_id>[0-9]+)/)?$', views.update_overtime_task, name='update_overtime_task'),
    url(r'^overtime/delete/(?P<ot_id>[0-9]+)/$', views.overtime_task_delete, name='overtime_task_delete'),
    url(r'^overtime/submit/(?P<ot_id>[0-9]+)/$', views.overtime_task_submit, name='overtime_task_submit'),
    url(r'^overtime/withdraw/(?P<ot_id>[0-9]+)/$', views.overtime_task_withdraw, name='overtime_task_withdraw'),

    url(r'^overtime/subordinate_tasks/$', views.subordinate_overtime_tasks, name='subordinate_overtime_tasks'),
    url(r'^overtime/approve/(?P<ot_id>[0-9]+)/$', views.overtime_task_approve, name='overtime_task_approve'),
    url(r'^overtime/negative/(?P<ot_id>[0-9]+)/$', views.overtime_task_negative, name='overtime_task_negative'),

    url(r'^cost/$', views.my_cost_tasks, name='my_cost_tasks'),
    url(r'^cost/add/$', views.add_cost_task, name='add_cost_task'),
    url(r'^cost/(?P<ct_id>[0-9]+)/$', views.cost_task_detail, name='cost_task_detail'),
    url(r'^cost/update/(?:(?P<ct_id>[0-9]+)/)?$', views.update_cost_task, name='update_cost_task'),
    url(r'^cost/delete/(?P<ct_id>[0-9]+)/$', views.cost_task_delete, name='cost_task_delete'),
    url(r'^cost/submit/(?P<ct_id>[0-9]+)/$', views.cost_task_submit, name='cost_task_submit'),
    url(r'^cost/withdraw/(?P<ct_id>[0-9]+)/$', views.cost_task_withdraw, name='cost_task_withdraw'),

    url(r'^cost/subordinate_tasks/$', views.subordinate_cost_tasks, name='subordinate_cost_tasks'),
    url(r'^cost/approve/(?P<ct_id>[0-9]+)/$', views.cost_task_approve, name='cost_task_approve'),
    url(r'^cost/negative/(?P<ct_id>[0-9]+)/$', views.cost_task_negative, name='cost_task_negative'),
    ]

oa_core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from business.util import DeanUtil
from ckeditor_uploader.fields import RichTextUploadingField

def user_directory_path(instance, filename):
    #file_name可以获取文件本来的名称，这里进行文件名的md5化,现在文件将会存储在Mida_root/uploads/ymd/xxx
    print 'user_directory_path method filename:', filename
    file_suffix = filename.split('.')[-1]
    md5_filename = DeanUtil.generate_md5(filename)
    print 'then md5_filename:', md5_filename
    date_str = DeanUtil.now_date_str()
    return ('uploads/' + date_str + '/{0}.' + file_suffix).format(md5_filename)

class Ceo(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=20)
    #0女 1男
    sex = models.IntegerField(null=True, default=1)
    phone = models.CharField(max_length=20, null=True)
    email = models.CharField(max_length=30, null=True)
    photo = models.ImageField(upload_to=user_directory_path, null=True)
    password = models.CharField(max_length=20)
    dept = models.CharField(max_length=20, default='CEO')

    def __unicode__(self):
        return self.name


class Manager(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=20)
    sex = models.IntegerField(null=True, default=1)
    phone = models.CharField(max_length=20,null=True)
    email = models.CharField(max_length=30,null=True)
    photo = models.ImageField(upload_to=user_directory_path, null=True)
    password = models.CharField(max_length=20)
    ceo = models.ForeignKey(Ceo, null=True)
    dept = models.OneToOneField('Department', null=True, related_name='dept_of')

    def __unicode__(self):
        return self.name


class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    manager = models.OneToOneField(Manager, null=True, related_name='manager_of')

    def __unicode__(self):
        return self.name


class Employee(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=20)
    sex = models.IntegerField(null=True, default=1)
    job = models.CharField(max_length=20, null=True)
    phone = models.CharField(max_length=20, null=True)
    email = models.CharField(max_length=30, null=True)
    photo = models.ImageField(upload_to=user_directory_path, null=True)
    password = models.CharField(max_length=20)
    register_time = models.DateTimeField()
    dept = models.ForeignKey(Department, null=True)

    def __unicode__(self):
        return self.name


class HolidayTask(models.Model):
    id = models.AutoField(primary_key=True)
    # 0事假，1病假，2婚假，3产假，4年假
    type = models.IntegerField(null=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    days = models.IntegerField(null=True)
    comment = models.CharField(max_length=200, null=True)
    dept_name = models.CharField(max_length=20, null=True)
    # 逻辑外键，发起人
    sponsor = models.CharField(max_length=10, null=True)
    # 逻辑外键，发起人的直接上级
    straight_upper = models.CharField(max_length=10, null=True)
    create_date_time = models.DateTimeField(null=True)
    submit_date_time = models.DateTimeField(null=True)
    approve_date_time = models.DateTimeField(null=True)
    # 0新建 1提交 2同意 3驳回
    status = models.IntegerField(null=True)

    def __unicode__(self):
        return str(self.id)


class OvertimeTask(models.Model):
    id = models.AutoField(primary_key=True)
    overtime_date = models.DateField(null=True)
    start_hour = models.IntegerField(null=True)
    end_hour = models.IntegerField(null=True)
    hours = models.IntegerField(null=True)
    comment = models.CharField(max_length=200, null=True)
    dept_name = models.CharField(max_length=20, null=True)
    # 逻辑外键，发起人
    sponsor = models.CharField(max_length=10, null=True)
    # 逻辑外键，发起人的直接上级
    straight_upper = models.CharField(max_length=10, null=True)
    create_date_time = models.DateTimeField(null=True)
    submit_date_time = models.DateTimeField(null=True)
    approve_date_time = models.DateTimeField(null=True)
    # 0新建 1提交 2同意 3驳回
    status = models.IntegerField(null=True)

    def __unicode__(self):
        return str(self.id)


class CostTask(models.Model):
    id = models.AutoField(primary_key=True)
    # 报销类型  0差旅 1采购 2业务招待
    type = models.IntegerField(null=True)
    comment = models.CharField(max_length=200, null=True)
    amount = models.FloatField(null=True)
    dept_name = models.CharField(max_length=20, null=True)
    # 逻辑外键，发起人
    sponsor = models.CharField(max_length=10, null=True)
    # 逻辑外键，发起人的直接上级
    straight_upper = models.CharField(max_length=10, null=True)
    create_date_time = models.DateTimeField(null=True)
    submit_date_time = models.DateTimeField(null=True)
    approve_date_time = models.DateTimeField(null=True)
    # 0新建 1提交 2同意 3驳回
    status = models.IntegerField(null=True)

    def __unicode__(self):
        return str(self.id)


class News(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    content = RichTextUploadingField()
    # 逻辑外键，创建人
    sponsor = models.CharField(max_length=10)
    create_date = models.DateField()

    def __unicode__(self):
        return str(self.id)

oa_core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from business.employee import Employee
from business.common import Common
from business.util import DeanUtil
from business.holiday_task import HolidayTask
from business.overtime_task import OvertimeTask
from business.cost_task import CostTask
from business.dean_annotation import *
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from models import HolidayTask as model_HolidayTask, OvertimeTask as model_OvertimeTask, CostTask as model_CostTask

employee = Employee()
common = Common()
holiday_task = HolidayTask()
overtime_task = OvertimeTask()
cost_task = CostTask()
util = DeanUtil


def em_register(request):
    global employee
    return employee.em_register(request)


def register_success(request):
    global common
    return common.register_success(request)


def login(request):
    global common
    return common.user_login(request)


@require_GET
def index(request):
    global common
    return common.go_index(request)


@has_login
@require_GET
def logout(request):
    global common
    return common.logout(request)


@has_login
@require_GET
def user_center(request):
    global common
    user = request.session.get('user')
    return common.user_center(request, user)


@has_login
def user_info_update(request):
    global common
    return common.user_info_update(request)


@has_login
def user_detail(request, user_id):
    global common
    return common.user_detail(request, user_id)


@has_login
def user_password_update(request):
    global common
    return common.user_password_update(request)


@has_login
@require_GET
def all_employees(request):
    global common
    return common.all_employees(request)


@has_login
@require_GET
def all_managers(request):
    global common
    return common.all_managers(request)


@has_login
@require_GET
def all_ceo(request):
    global common
    return common.all_ceo(request)


@has_login
@require_GET
def company_news(request):
    global common
    return common.company_news(request)


@has_login
@require_GET
def show_news(request, news_id):
    global common
    return common.show_news(request, news_id)


@has_login
@require_GET
def my_holiday_tasks(request):
    global holiday_task
    return holiday_task.my_holiday_tasks(request)


@has_login
def add_holiday_task(request):
    global holiday_task
    return holiday_task.add_holiday_task(request)


@has_login
@require_GET
def holiday_task_detail(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_detail(request, ht_id=ht_id)


@has_login
@can_update(id_name='ht_id', model_class=model_HolidayTask)
def update_holiday_task(request, ht_id=None):
    global holiday_task
    return holiday_task.update_holiday_task(request, ht_id=ht_id)

@has_login
@can_do(cur_status=0, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_delete(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_delete(request, ht_id)

@has_login
@can_do(cur_status=0, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_submit(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_submit(request, ht_id)

@has_login
@can_do(cur_status=1, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_withdraw(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_withdraw(request, ht_id)


@has_login
@require_GET
def subordinate_holiday_tasks(request):
    global holiday_task
    return holiday_task.subordinate_holiday_tasks(request)


@has_login
@can_do(cur_status=1, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_approve(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_approve(request, ht_id)


@has_login
@can_do(cur_status=1, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_negative(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_negative(request, ht_id)



@has_login
@require_GET
def my_overtime_tasks(request):
    global overtime_task
    return overtime_task.my_overtime_tasks(request)


@has_login
def add_overtime_task(request):
    global overtime_task
    return overtime_task.add_overtime_task(request)


@has_login
@require_GET
def overtime_task_detail(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_detail(request, ot_id=ot_id)


@has_login
@can_update(id_name='ot_id', model_class=model_OvertimeTask)
def update_overtime_task(request, ot_id=None):
    global overtime_task
    return overtime_task.update_overtime_task(request, ot_id=ot_id)


@has_login
@can_do(cur_status=0, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_delete(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_delete(request, ot_id)


@has_login
@can_do(cur_status=0, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_submit(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_submit(request, ot_id)


@has_login
@can_do(cur_status=1, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_withdraw(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_withdraw(request, ot_id)


@has_login
@require_GET
def subordinate_overtime_tasks(request):
    global overtime_task
    return overtime_task.subordinate_overtime_tasks(request)


@has_login
@can_do(cur_status=1, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_approve(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_approve(request, ot_id)


@has_login
@can_do(cur_status=1, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_negative(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_negative(request, ot_id)


@has_login
@require_GET
def my_cost_tasks(request):
    global cost_task
    return cost_task.my_cost_tasks(request)


@has_login
def add_cost_task(request):
    # pass
    global cost_task
    return cost_task.add_cost_task(request)


@has_login
@require_GET
def cost_task_detail(request, ct_id):
    # pass
    global cost_task
    return cost_task.cost_task_detail(request, ct_id=ct_id)


@has_login
@can_update(id_name='ct_id', model_class=model_CostTask)
def update_cost_task(request, ct_id=None):
    # pass
    global cost_task
    return cost_task.update_cost_task(request, ct_id=ct_id)


@has_login
@can_do(cur_status=0, id_name='ct_id', model_class=model_CostTask)
def cost_task_delete(request, ct_id):
    global cost_task
    return cost_task.cost_task_delete(request, ct_id)


@has_login
@can_do(cur_status=0, id_name='ct_id', model_class=model_CostTask)
def cost_task_submit(request, ct_id):
    global cost_task
    return cost_task.cost_task_submit(request, ct_id)


@has_login
@can_do(cur_status=1, id_name='ct_id', model_class=model_CostTask)
def cost_task_withdraw(request, ct_id):
    global cost_task
    return cost_task.cost_task_withdraw(request, ct_id)



@has_login
@require_GET
def subordinate_cost_tasks(request):
    global cost_task
    return cost_task.subordinate_cost_tasks(request)


@has_login
@can_do(cur_status=1, id_name='ct_id', model_class=model_CostTask)
def cost_task_approve(request, ct_id):
    global cost_task
    return cost_task.cost_task_approve(request, ct_id)


@has_login
@can_do(cur_status=1, id_name='ct_id', model_class=model_CostTask)
def cost_task_negative(request, ct_id):
    global cost_task
    return cost_task.cost_task_negative(request, ct_id)

oa_core/templates/oa_core/overtime/detail.html
{% extends "../index.html" %}

{% block title %}
    加班申请详情
{% endblock title%}

{% block content %}
    <div class="container" style="margin-top: 70px">
        <div class="row">
            <div class="col-md-3 col-md-offset-5">
                <h3>加班申请单内容</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form action="{% url 'oa_core:update_overtime_task' %}" method="post" id="update_form">
                    <div class="form-group">
                        <label for="overtime_date">加班日期</label>
                        <input type="text" class="form-control" id="overtime_date" name="overtime_date"
                               value="{{ overtime_date | date:'Y-m-d'}}" readonly>
                        <span class="error-message" name="overtime_date"></span>
                    </div>
                    <div class="form-group">
                        <label for="start_hour">开始时间</label>
                        <input type="number" class="form-control" id="start_hour" name="start_hour" max="23" min="0"
                                value="{{ start_hour }}" readonly>
                        <span class="error-message" name="start_hour"></span>
                    </div>
                    <div class="form-group">
                        <label for="end_hour">结束时间</label>
                        <input type="number" class="form-control" id="end_hour" name="end_hour" max="23" min="0"
                                value="{{ end_hour }}" readonly>
                        <span class="error-message" name="end_hour"></span>
                    </div>
                    <div class="form-group">
                        <label for="comment">备注</label>
                        <textarea class="form-control" rows="3" name="comment" id="comment" readonly>{{ comment }}</textarea>
                        <span class="error-message" name="comment"></span>
                    </div>
                    <div class="form-group">
                        <label for="dept_name">部门名称</label>
                        <input class="form-control" name="dept_name" id="dept_name" value="{{dept_name}}" readonly/>
                    </div>
                    <div class="form-group">
                        <label for="sponsor">申请人</label>
                        <input class="form-control" name="sponsor" id="sponsor" value="{{ sponsor }}" readonly/>
                    </div>
                    <div class="form-group">
                        <label for="straight_upper">可审批人</label>
                        <input class="form-control" name="straight_upper" id="straight_upper" value="{{ straight_upper }}" readonly/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{%endblock content%}

oa_core/templates/oa_core/overtime/search.html
{% extends "../index.html" %}
{% load static %}
{% load custom_filters %}
{% block title %}
    我的加班申请
{% endblock title%}

{% block css %}
    <link href="{% static 'oa_core/kkpager/src/kkpager_blue.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 20px">
            <div class="col-md-10 col-md-offset-2">
                <form class="form-inline" action="{% url 'oa_core:my_overtime_tasks' %}" id="search_form">
                    {% csrf_token %}
                    <div class="form-group clearfix">
                        <label for="create_date">创建日期下限</label>
                        <input type="text" class="form-control" id="create_date" name="create_date"
                               value="{{ search_condition.create_date|default_if_none:'' |date:"Y-m-d"}}">
                    </div>

                    <div class="form-group" style="margin-left: 10px">
                        <label for="status">状态</label>
                        <select class="form-control" name="status" id="status">
                            <option value="">全部</option>
                            <option value="0"
                                {% if search_condition.status == 0 %}
                                    selected
                                {% endif %}
                            >新建</option>
                            <option value="1"
                                {% if search_condition.status == 1 %}
                                    selected
                                {% endif %}
                            >提交</option>
                            <option value="2"
                                {% if search_condition.status == 2 %}
                                    selected
                                {% endif %}
                            >同意</option>
                            <option value="3"
                                {% if search_condition.status == 3 %}
                                    selected
                                {% endif %}
                            >驳回</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary" style="margin-left: 30px">查询</button>
                </form>
            </div>
        </div>

        <div class="row" style="margin-top: 20px">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th>id</th>
                            <th>create_date_time</th>
                            <th>detail</th>
                            <th>operation</th>
                            <th>current_status</th>
                        </tr>
                        {% for o_task in page_obj.object_list %}
                        <tr>
                            <td>{{ o_task.id}}</td>
                            <td>{{ o_task.create_date_time | date:"Y-m-d h:i:s"}}</td>
                            <td><a href="{% url 'oa_core:overtime_task_detail' o_task.id%}">详情</a></td>
                            <td>
                                {% if o_task.status  == 0 %}
                                    <a href="{% url 'oa_core:overtime_task_delete' o_task.id %}">删除</a>|
                                    <a href="{% url 'oa_core:update_overtime_task' o_task.id %}">修改</a>|
                                    <a href="{% url 'oa_core:overtime_task_submit' o_task.id %}">提交</a>
                                {% elif o_task.status  == 1 %}
                                    <a href="{% url 'oa_core:overtime_task_withdraw' o_task.id %}">撤回</a>
                                {% else %}
                                    --
                                {% endif %}
                            </td>
                            <td>{{ o_task.status | current_status }}</td>
                        </tr>
                        {% empty %}
                            <li>Sorry, no overtime Task.</li>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                    <div id="kkpager"></div>
            </div>
        </div>
        <a class="btn  btn-warning pull-right" href="{% url "oa_core:add_overtime_task" %}">新建加班申请</a>
    </div>

{%endblock content%}

{% block js %}
    <script src="{% static 'oa_core/layDate-v5.0.9/laydate/laydate.js' %}"></script>
    <script src="{% static 'oa_core/kkpager/src/kkpager.min.js' %}"></script>
    <script>
        //国际版
        laydate.render({
          elem: '#create_date'
          ,lang: 'en'
        });

        //init kkpager
        $(function(){
            var totalPage = {{ page_obj.paginator.num_pages }};
            var totalRecords = {{ page_obj.paginator.count }};
            var pageNo = {{ page_obj.number }}
            //生成分页
            //有些参数是可选的，比如lang，若不传有默认值
            kkpager.generPageHtml({
                pno : pageNo,
                //总页码
                total : totalPage,
                //总数据条数
                totalRecords : totalRecords,
                //链接前部
                hrefFormer : '{% url "oa_core:my_overtime_tasks" %}',
                //链接尾部
                hrefLatter : "&create_date={{ search_condition.create_date |default_if_none:'' |date:'Y-m-d'}}"
                             +"&status={{ search_condition.status |default_if_none:'' }}",
                getLink : function(n){
                    return this.hrefFormer +"?page_no="+n + this.hrefLatter;
                }
            });
        });
    </script>
{% endblock %}

oa_core/templates/oa_core/overtime/sp_search.html
{% extends "../index.html" %}
{% load static %}
{% load custom_filters %}
{% block title %}
    审批加班申请
{% endblock title%}

{% block css %}
    <link href="{% static 'oa_core/kkpager/src/kkpager_blue.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 20px">
            <div class="col-md-10 col-md-offset-2">
                <form class="form-inline" action="{% url 'oa_core:subordinate_overtime_tasks' %}" id="search_form">
                    {% csrf_token %}
                    <div class="form-group clearfix">
                        <label for="create_date">提交日期下限</label>
                        <input type="text" class="form-control" id="create_date" name="create_date"
                               value="{{ search_condition.create_date|default_if_none:'' |date:"Y-m-d"}}">
                    </div>

                    <div class="form-group" style="margin-left: 10px">
                        <label for="status">状态</label>
                        <select class="form-control" name="status" id="status">
                            <option value="">全部</option>
                            <option value="1"
                                {% if search_condition.status == 1 %}
                                    selected
                                {% endif %}
                            >提交</option>
                            <option value="2"
                                {% if search_condition.status == 2 %}
                                    selected
                                {% endif %}
                            >同意</option>
                            <option value="3"
                                {% if search_condition.status == 3 %}
                                    selected
                                {% endif %}
                            >驳回</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary" style="margin-left: 30px">查询</button>
                </form>
            </div>
        </div>

        <div class="row" style="margin-top: 20px">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tr>
                            <th>id</th>
                            <th>submit_date_time</th>
                            <th>detail</th>
                            <th>operation</th>
                            <th>current_status</th>
                        </tr>
                        {% for o_task in page_obj.object_list %}
                        <tr>
                            <td>{{ o_task.id}}</td>
                            <td>{{ o_task.submit_date_time | date:"Y-m-d h:i:s"}}</td>
                            <td><a href="{% url 'oa_core:overtime_task_detail' o_task.id%}">详情</a></td>
                            <td>
                                {% if o_task.status  == 1 %}
                                    <a href="{% url 'oa_core:overtime_task_approve' o_task.id %}">同意</a>|
                                    <a href="{% url 'oa_core:overtime_task_negative' o_task.id %}">驳回</a>
                                {% else %}
                                    --
                                {% endif %}
                            </td>
                            <td>{{ o_task.status | current_status }}</td>
                        </tr>
                        {% empty %}
                            <li>Sorry, no overtime Task submit to here.</li>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                    <div id="kkpager"></div>
            </div>
        </div>
    </div>

{%endblock content%}

{% block js %}
    <script src="{% static 'oa_core/layDate-v5.0.9/laydate/laydate.js' %}"></script>
    <script src="{% static 'oa_core/kkpager/src/kkpager.min.js' %}"></script>
    <script>
        //国际版
        laydate.render({
          elem: '#create_date'
          ,lang: 'en'
        });

        //init kkpager
        $(function(){
            var totalPage = {{ page_obj.paginator.num_pages }};
            var totalRecords = {{ page_obj.paginator.count }};
            var pageNo = {{ page_obj.number }}
            //生成分页
            //有些参数是可选的，比如lang，若不传有默认值
            kkpager.generPageHtml({
                pno : pageNo,
                //总页码
                total : totalPage,
                //总数据条数
                totalRecords : totalRecords,
                //链接前部
                hrefFormer : '{% url "oa_core:subordinate_overtime_tasks" %}',
                //链接尾部
                hrefLatter : "&create_date={{ search_condition.create_date |default_if_none:'' |date:'Y-m-d'}}"
                             +"&status={{ search_condition.status |default_if_none:'' }}",
                getLink : function(n){
                    return this.hrefFormer +"?page_no="+n + this.hrefLatter;
                }
            });
        });
    </script>
{% endblock %}