my_oa_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^oa_core/', include('oa_core.urls', namespace="oa_core")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls'))
]

oa_core/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    # post views
    url(r'^register/$', views.em_register, name='register'),
    url(r'^register_success/$', views.register_success, name='register_success'),
    url(r'^login/$', views.login, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^user_center/$', views.user_center, name='user_center'),
    url(r'^user_info_update/$', views.user_info_update, name='user_info_update'),
    url(r'^user_password_update/$', views.user_password_update, name='user_password_update'),
    url(r'^all_employees/$', views.all_employees, name='all_employees'),
    url(r'^all_managers/$', views.all_managers, name='all_managers'),
    url(r'^all_ceo/$', views.all_ceo, name='all_ceo'),
    url(r'^user_detail/(?P<user_id>[emc]_[0-9]+)/$', views.user_detail, name='user_detail'),
    url(r'^company_news/$', views.company_news, name='company_news'),
    url(r'^show_news/(?P<news_id>[0-9]+)$', views.show_news, name='show_news'),



    url(r'^holiday/$', views.my_holiday_tasks, name='my_holiday_tasks'),
    url(r'^holiday/add/$', views.add_holiday_task, name='add_holiday_task'),
    url(r'^holiday/(?P<ht_id>[0-9]+)/$', views.holiday_task_detail, name='holiday_task_detail'),
    url(r'^holiday/update/(?:(?P<ht_id>[0-9]+)/)?$', views.update_holiday_task, name='update_holiday_task'),
    url(r'^holiday/delete/(?P<ht_id>[0-9]+)/$', views.holiday_task_delete, name='holiday_task_delete'),
    url(r'^holiday/submit/(?P<ht_id>[0-9]+)/$', views.holiday_task_submit, name='holiday_task_submit'),
    url(r'^holiday/withdraw/(?P<ht_id>[0-9]+)/$', views.holiday_task_withdraw, name='holiday_task_withdraw'),

    url(r'^holiday/subordinate_tasks/$', views.subordinate_holiday_tasks, name='subordinate_holiday_tasks'),
    url(r'^holiday/approve/(?P<ht_id>[0-9]+)/$', views.holiday_task_approve, name='holiday_task_approve'),
    url(r'^holiday/negative/(?P<ht_id>[0-9]+)/$', views.holiday_task_negative, name='holiday_task_negative'),

    url(r'^overtime/$', views.my_overtime_tasks, name='my_overtime_tasks'),
    url(r'^overtime/add/$', views.add_overtime_task, name='add_overtime_task'),
    url(r'^overtime/(?P<ot_id>[0-9]+)/$', views.overtime_task_detail, name='overtime_task_detail'),
    url(r'^overtime/update/(?:(?P<ot_id>[0-9]+)/)?$', views.update_overtime_task, name='update_overtime_task'),
    url(r'^overtime/delete/(?P<ot_id>[0-9]+)/$', views.overtime_task_delete, name='overtime_task_delete'),
    url(r'^overtime/submit/(?P<ot_id>[0-9]+)/$', views.overtime_task_submit, name='overtime_task_submit'),
    url(r'^overtime/withdraw/(?P<ot_id>[0-9]+)/$', views.overtime_task_withdraw, name='overtime_task_withdraw'),

    url(r'^overtime/subordinate_tasks/$', views.subordinate_overtime_tasks, name='subordinate_overtime_tasks'),
    url(r'^overtime/approve/(?P<ot_id>[0-9]+)/$', views.overtime_task_approve, name='overtime_task_approve'),
    url(r'^overtime/negative/(?P<ot_id>[0-9]+)/$', views.overtime_task_negative, name='overtime_task_negative'),

    url(r'^cost/$', views.my_cost_tasks, name='my_cost_tasks'),
    url(r'^cost/add/$', views.add_cost_task, name='add_cost_task'),
    url(r'^cost/(?P<ct_id>[0-9]+)/$', views.cost_task_detail, name='cost_task_detail'),
    url(r'^cost/update/(?:(?P<ct_id>[0-9]+)/)?$', views.update_cost_task, name='update_cost_task'),
    url(r'^cost/delete/(?P<ct_id>[0-9]+)/$', views.cost_task_delete, name='cost_task_delete'),
    url(r'^cost/submit/(?P<ct_id>[0-9]+)/$', views.cost_task_submit, name='cost_task_submit'),
    url(r'^cost/withdraw/(?P<ct_id>[0-9]+)/$', views.cost_task_withdraw, name='cost_task_withdraw'),

    url(r'^cost/subordinate_tasks/$', views.subordinate_cost_tasks, name='subordinate_cost_tasks'),
    url(r'^cost/approve/(?P<ct_id>[0-9]+)/$', views.cost_task_approve, name='cost_task_approve'),
    url(r'^cost/negative/(?P<ct_id>[0-9]+)/$', views.cost_task_negative, name='cost_task_negative'),
    ]

oa_core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from business.util import DeanUtil
from ckeditor_uploader.fields import RichTextUploadingField

def user_directory_path(instance, filename):
    #file_name可以获取文件本来的名称，这里进行文件名的md5化,现在文件将会存储在Mida_root/uploads/ymd/xxx
    print 'user_directory_path method filename:', filename
    file_suffix = filename.split('.')[-1]
    md5_filename = DeanUtil.generate_md5(filename)
    print 'then md5_filename:', md5_filename
    date_str = DeanUtil.now_date_str()
    return ('uploads/' + date_str + '/{0}.' + file_suffix).format(md5_filename)

class Ceo(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=20)
    #0女 1男
    sex = models.IntegerField(null=True, default=1)
    phone = models.CharField(max_length=20, null=True)
    email = models.CharField(max_length=30, null=True)
    photo = models.ImageField(upload_to=user_directory_path, null=True)
    password = models.CharField(max_length=20)
    dept = models.CharField(max_length=20, default='CEO')

    def __unicode__(self):
        return self.name


class Manager(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=20)
    sex = models.IntegerField(null=True, default=1)
    phone = models.CharField(max_length=20,null=True)
    email = models.CharField(max_length=30,null=True)
    photo = models.ImageField(upload_to=user_directory_path, null=True)
    password = models.CharField(max_length=20)
    ceo = models.ForeignKey(Ceo, null=True)
    dept = models.OneToOneField('Department', null=True, related_name='dept_of')

    def __unicode__(self):
        return self.name


class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    manager = models.OneToOneField(Manager, null=True, related_name='manager_of')

    def __unicode__(self):
        return self.name


class Employee(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=20)
    sex = models.IntegerField(null=True, default=1)
    job = models.CharField(max_length=20, null=True)
    phone = models.CharField(max_length=20, null=True)
    email = models.CharField(max_length=30, null=True)
    photo = models.ImageField(upload_to=user_directory_path, null=True)
    password = models.CharField(max_length=20)
    register_time = models.DateTimeField()
    dept = models.ForeignKey(Department, null=True)

    def __unicode__(self):
        return self.name


class HolidayTask(models.Model):
    id = models.AutoField(primary_key=True)
    # 0事假，1病假，2婚假，3产假，4年假
    type = models.IntegerField(null=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    days = models.IntegerField(null=True)
    comment = models.CharField(max_length=200, null=True)
    dept_name = models.CharField(max_length=20, null=True)
    # 逻辑外键，发起人
    sponsor = models.CharField(max_length=10, null=True)
    # 逻辑外键，发起人的直接上级
    straight_upper = models.CharField(max_length=10, null=True)
    create_date_time = models.DateTimeField(null=True)
    submit_date_time = models.DateTimeField(null=True)
    approve_date_time = models.DateTimeField(null=True)
    # 0新建 1提交 2同意 3驳回
    status = models.IntegerField(null=True)

    def __unicode__(self):
        return str(self.id)


class OvertimeTask(models.Model):
    id = models.AutoField(primary_key=True)
    overtime_date = models.DateField(null=True)
    start_hour = models.IntegerField(null=True)
    end_hour = models.IntegerField(null=True)
    hours = models.IntegerField(null=True)
    comment = models.CharField(max_length=200, null=True)
    dept_name = models.CharField(max_length=20, null=True)
    # 逻辑外键，发起人
    sponsor = models.CharField(max_length=10, null=True)
    # 逻辑外键，发起人的直接上级
    straight_upper = models.CharField(max_length=10, null=True)
    create_date_time = models.DateTimeField(null=True)
    submit_date_time = models.DateTimeField(null=True)
    approve_date_time = models.DateTimeField(null=True)
    # 0新建 1提交 2同意 3驳回
    status = models.IntegerField(null=True)

    def __unicode__(self):
        return str(self.id)


class CostTask(models.Model):
    id = models.AutoField(primary_key=True)
    # 报销类型  0差旅 1采购 2业务招待
    type = models.IntegerField(null=True)
    comment = models.CharField(max_length=200, null=True)
    amount = models.FloatField(null=True)
    dept_name = models.CharField(max_length=20, null=True)
    # 逻辑外键，发起人
    sponsor = models.CharField(max_length=10, null=True)
    # 逻辑外键，发起人的直接上级
    straight_upper = models.CharField(max_length=10, null=True)
    create_date_time = models.DateTimeField(null=True)
    submit_date_time = models.DateTimeField(null=True)
    approve_date_time = models.DateTimeField(null=True)
    # 0新建 1提交 2同意 3驳回
    status = models.IntegerField(null=True)

    def __unicode__(self):
        return str(self.id)


class News(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    content = RichTextUploadingField()
    # 逻辑外键，创建人
    sponsor = models.CharField(max_length=10)
    create_date = models.DateField()

    def __unicode__(self):
        return str(self.id)

oa_core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from business.employee import Employee
from business.common import Common
from business.util import DeanUtil
from business.holiday_task import HolidayTask
from business.overtime_task import OvertimeTask
from business.cost_task import CostTask
from business.dean_annotation import *
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from models import HolidayTask as model_HolidayTask, OvertimeTask as model_OvertimeTask, CostTask as model_CostTask

employee = Employee()
common = Common()
holiday_task = HolidayTask()
overtime_task = OvertimeTask()
cost_task = CostTask()
util = DeanUtil


def em_register(request):
    global employee
    return employee.em_register(request)


def register_success(request):
    global common
    return common.register_success(request)


def login(request):
    global common
    return common.user_login(request)


@require_GET
def index(request):
    global common
    return common.go_index(request)


@has_login
@require_GET
def logout(request):
    global common
    return common.logout(request)


@has_login
@require_GET
def user_center(request):
    global common
    user = request.session.get('user')
    return common.user_center(request, user)


@has_login
def user_info_update(request):
    global common
    return common.user_info_update(request)


@has_login
def user_detail(request, user_id):
    global common
    return common.user_detail(request, user_id)


@has_login
def user_password_update(request):
    global common
    return common.user_password_update(request)


@has_login
@require_GET
def all_employees(request):
    global common
    return common.all_employees(request)


@has_login
@require_GET
def all_managers(request):
    global common
    return common.all_managers(request)


@has_login
@require_GET
def all_ceo(request):
    global common
    return common.all_ceo(request)


@has_login
@require_GET
def company_news(request):
    global common
    return common.company_news(request)


@has_login
@require_GET
def show_news(request, news_id):
    global common
    return common.show_news(request, news_id)


@has_login
@require_GET
def my_holiday_tasks(request):
    global holiday_task
    return holiday_task.my_holiday_tasks(request)


@has_login
def add_holiday_task(request):
    global holiday_task
    return holiday_task.add_holiday_task(request)


@has_login
@require_GET
def holiday_task_detail(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_detail(request, ht_id=ht_id)


@has_login
@can_update(id_name='ht_id', model_class=model_HolidayTask)
def update_holiday_task(request, ht_id=None):
    global holiday_task
    return holiday_task.update_holiday_task(request, ht_id=ht_id)

@has_login
@can_do(cur_status=0, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_delete(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_delete(request, ht_id)

@has_login
@can_do(cur_status=0, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_submit(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_submit(request, ht_id)

@has_login
@can_do(cur_status=1, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_withdraw(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_withdraw(request, ht_id)


@has_login
@require_GET
def subordinate_holiday_tasks(request):
    global holiday_task
    return holiday_task.subordinate_holiday_tasks(request)


@has_login
@can_do(cur_status=1, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_approve(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_approve(request, ht_id)


@has_login
@can_do(cur_status=1, id_name='ht_id', model_class=model_HolidayTask)
def holiday_task_negative(request, ht_id):
    global holiday_task
    return holiday_task.holiday_task_negative(request, ht_id)



@has_login
@require_GET
def my_overtime_tasks(request):
    global overtime_task
    return overtime_task.my_overtime_tasks(request)


@has_login
def add_overtime_task(request):
    global overtime_task
    return overtime_task.add_overtime_task(request)


@has_login
@require_GET
def overtime_task_detail(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_detail(request, ot_id=ot_id)


@has_login
@can_update(id_name='ot_id', model_class=model_OvertimeTask)
def update_overtime_task(request, ot_id=None):
    global overtime_task
    return overtime_task.update_overtime_task(request, ot_id=ot_id)


@has_login
@can_do(cur_status=0, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_delete(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_delete(request, ot_id)


@has_login
@can_do(cur_status=0, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_submit(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_submit(request, ot_id)


@has_login
@can_do(cur_status=1, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_withdraw(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_withdraw(request, ot_id)


@has_login
@require_GET
def subordinate_overtime_tasks(request):
    global overtime_task
    return overtime_task.subordinate_overtime_tasks(request)


@has_login
@can_do(cur_status=1, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_approve(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_approve(request, ot_id)


@has_login
@can_do(cur_status=1, id_name='ot_id', model_class=model_OvertimeTask)
def overtime_task_negative(request, ot_id):
    global overtime_task
    return overtime_task.overtime_task_negative(request, ot_id)


@has_login
@require_GET
def my_cost_tasks(request):
    global cost_task
    return cost_task.my_cost_tasks(request)


@has_login
def add_cost_task(request):
    # pass
    global cost_task
    return cost_task.add_cost_task(request)


@has_login
@require_GET
def cost_task_detail(request, ct_id):
    # pass
    global cost_task
    return cost_task.cost_task_detail(request, ct_id=ct_id)


@has_login
@can_update(id_name='ct_id', model_class=model_CostTask)
def update_cost_task(request, ct_id=None):
    # pass
    global cost_task
    return cost_task.update_cost_task(request, ct_id=ct_id)


@has_login
@can_do(cur_status=0, id_name='ct_id', model_class=model_CostTask)
def cost_task_delete(request, ct_id):
    global cost_task
    return cost_task.cost_task_delete(request, ct_id)


@has_login
@can_do(cur_status=0, id_name='ct_id', model_class=model_CostTask)
def cost_task_submit(request, ct_id):
    global cost_task
    return cost_task.cost_task_submit(request, ct_id)


@has_login
@can_do(cur_status=1, id_name='ct_id', model_class=model_CostTask)
def cost_task_withdraw(request, ct_id):
    global cost_task
    return cost_task.cost_task_withdraw(request, ct_id)



@has_login
@require_GET
def subordinate_cost_tasks(request):
    global cost_task
    return cost_task.subordinate_cost_tasks(request)


@has_login
@can_do(cur_status=1, id_name='ct_id', model_class=model_CostTask)
def cost_task_approve(request, ct_id):
    global cost_task
    return cost_task.cost_task_approve(request, ct_id)


@has_login
@can_do(cur_status=1, id_name='ct_id', model_class=model_CostTask)
def cost_task_negative(request, ct_id):
    global cost_task
    return cost_task.cost_task_negative(request, ct_id)

oa_core/templates/oa_core/assign_code.html
{% extends "oa_core/base.html" %}
{% load static %}
{% block title %}assign code{% endblock %}
{% block css %}
    <link href="{% static 'oa_core/css/jumbotron-narrow.css' %}" rel="stylesheet">
{% endblock %}

{% block navbar %}{% endblock %}
{% block content %}
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="{% url 'oa_core:index' %}">Home</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Dean OA</h3>
      </div>

      <div class="jumbotron">
          <h2>registration success!</h2>
        <h1>Id code:{{ code }}</h1>
        <p class="lead">This code value will be the username for accessing Dean OA system! The generation process depends on the role of the user，
        it looks like a serial number。you can not modify it after you login, attention that！</p>
        <p><a class="btn btn-lg btn-success" href="{% url 'oa_core:login' %}" role="button">straightforward login</a></p>
      </div>
{%endblock content%}

oa_core/templates/oa_core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1.0,
                                     user-scalable=no">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>
    <link rel="icon" href="{% static 'oa_core/images/favicon2.png' %}">
    <!-- Bootstrap -->
    <link href="{% static 'oa_core/bootstrap_dist/css/bootstrap.min.css' %}" rel="stylesheet">


    <link href="{% static 'oa_core/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <script src="{% static 'oa_core/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block css %}{% endblock %}
  </head>
  <body>



  {% block navbar %}
    <!-- NAVBAR
    ================================================== -->
    <div class="navbar-wrapper">
      <div class="container">
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'oa_core:index' %}">Dean OA</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'oa_core:index' %}">Home</a></li>

                {% block navbar-left%}

                {% endblock %}
              </ul>
              <!--right side 默认登录注册-->
              {% block navbar-right %}
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'oa_core:login' %}">登录</a></li>
                    <li><a href="{% url 'oa_core:register' %}">注册</a></li>
                  </ul>
              {%  endblock%}
            </div>

          </div>
        </nav>
       </div>
    </div>
  {% endblock navbar %}
    <!-- Carousel
    ================================================== -->
    {% block content %}{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'oa_core/bootstrap_dist/js/bootstrap.min.js'%}"></script>

    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'oa_core/js/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'oa_core/js/ie10-viewport-bug-workaround.js' %}"></script>
    {% block js %}{% endblock %}
  </body>
</html>

oa_core/templates/oa_core/index.html
{% extends "oa_core/base.html" %}
{% load static %}
{% load  custom_filters%}
{% block title %}index{% endblock %}
{% block css %}
    <link href="{% static 'oa_core/css/carousel.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
      </ol>

      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static 'oa_core/images/office.jpg' %}" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static 'oa_core/images/office2.jpg' %}" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
          <div class="item">
          <img class="third-slide" src="{% static 'oa_core/images/office3.jpg' %}" alt="fifth slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
{% endblock %}



{% block navbar-left %}
    {% if request.session.user %}
        {% if request.session.role == 'e'%}
            <li><a href="{% url 'oa_core:my_holiday_tasks' %}">请假申请</a></li>
            <li><a href="{% url 'oa_core:my_overtime_tasks' %}">加班申请</a></li>
            <li><a href="{% url 'oa_core:my_cost_tasks' %}">报销申请</a></li>
        {% elif request.session.role == 'm'%}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">请假 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><a href="{% url 'oa_core:my_holiday_tasks' %}">请假申请</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'oa_core:subordinate_holiday_tasks' %}">请假审批</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">加班 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><a href="{% url 'oa_core:my_overtime_tasks' %}">加班申请</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'oa_core:subordinate_overtime_tasks' %}">加班审批</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">报销 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><a href="{% url 'oa_core:my_cost_tasks' %}">报销申请</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'oa_core:subordinate_cost_tasks' %}">报销审批</a></li>
              </ul>
            </li>
        {% elif request.session.role == 'c'%}
            <li><a href="{% url 'oa_core:subordinate_holiday_tasks' %}">请假审批</a></li>
            <li><a href="{% url 'oa_core:subordinate_overtime_tasks' %}">加班审批</a></li>
            <li><a href="{% url 'oa_core:subordinate_cost_tasks' %}">报销审批</a></li>
        {% endif %}
        <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">信息查询<span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><a href="{% url 'oa_core:all_employees' %}">员工</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'oa_core:all_managers' %}">部门经理</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'oa_core:all_ceo' %}">CEO</a></li>
              </ul>
        </li>
        <li><a href="{% url 'oa_core:company_news' %}">公司新闻</a></li>
        <li class="active"><a href="#" disabled>{{ request.session.user.dept }}</a></li>

    {% endif %}
{% endblock navbar-left %}

{% block navbar-right %}
      {% if request.session.user %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'oa_core:user_center' %}">个人中心</a></li>
            <li><a href="{% url 'oa_core:logout' %}">注销</a></li>
          </ul>
      {% else %}
          {{ block.super }}
      {% endif %}
{% endblock %}